# Site settings
title: l.g
email: l.gatsas33@gmail.com
description: "Hello, my Name is LucasGatsas. I'm a Designer & Front-End Engineer based in the City of Saint Gall, Switzerland. And this is my GitHub Contributions - Repositories - Public Activity Site!"
baseurl: ""
url: "https://spaceg.github.io"
twitter_username: LucasGatsas
github_username:  spaceg
google_username:  https://plus.google.com/101826267816845608605/posts

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page
