# lucas gatsas Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas Gatsas
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # "
  Lucas Gatsas, is a Web -Developer, Front -End Engineer & UI/UX Designer based in  St. Gallen, Switerland.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.lucasgatsas.ch" # the base hostname & protocol for your site

#These settings might be able to go?
author: Lucas Gatsas
twitter_username: lucasgatsas
github_username:  spaceg
company_name: lucasgatsas

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

